# Generated by Django 4.0.6 on 2022-08-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('company', models.CharField(choices=[('Google', 'Google'), ('Yandex', 'Yandex')], default='Google', max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('password_1', models.CharField(max_length=50)),
                ('password_2', models.CharField(max_length=50)),
            ],
        ),
    ]
