# Generated by Django 4.0.6 on 2022-08-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_1',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password_2',
            new_name='password',
        ),
    ]
